feat: Implement Ed25519 to Curve25519
Skycoder42/libsodium_dart_bindings pull request #54
Opened 2023-06-30 22:46 UTC by f-person

See https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519

2023-07-04 09:42 UTC, f-person commented
The tests are mostly copied from other methods in `SignSumo` and modified to fit. I wonder if it would be better to refactor them in a way to share the code or if it's fine the way it is :)

2023-07-13 04:54 UTC, Skycoder42 requested changes
Hi. I finally found the time to take a look at your changes. Looks mostly fine, except that the `crypto_sign_ed25519_sk_to_curve25519` converts a secret key to another secret key, which means the API should return a `SecureKey` instead of an `Uint8List`. Please take a look at my comments and fix the corresponding code.

Regarding the refactoring: Most of the code in this library looks very much alike, but with minor differences. For now, it is fine the way it is, as complex operations (like pointer management) have been extracted into their own classes and only the operations themselves remain. I personally would not extract the public key allocation, as it only moves the line somewhere else and at least in my opinion does not improve readability.

I am thinking about automating the code generation for the APIs on some abstract level, as that would streamline the implementations and allow me to easier implement the advanced APIs. However, as my time is limited, that is nothing I will investigate deeper in the near future.

Also, could you please rebase the PR? I think that should fix up the CI, so the pipeline can actually validate the PR is functionally correct ;)

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/lib/src/api/sumo/sign_sumo.dart
> +  Uint8List skToCurve25519(SecureKey secretKey);
As this method converts a secret key to a secret key, it should return `SecureKey` as well

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/lib/src/ffi/api/sumo/sign_sumo_ffi.dart
> +    final publicKey = _allocatePublicKey();
I don't think extracting a method for this one-liner is needed, as it does not increase readability here.

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/lib/src/ffi/api/sumo/sign_sumo_ffi.dart
> +    } finally {
This does not work properly. If `_allocatePublicKey` throws, then `ed25519PublicKey` will never be disposed. Instead, you should build this up similar to https://github.com/Skycoder42/libsodium_dart_bindings/blob/main/packages/sodium/lib/src/ffi/api/sign_ffi.dart#L105

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/lib/src/ffi/api/sumo/sign_sumo_ffi.dart
> +      publicKey.dispose();
It is fine here, as here there is only a single pointer to be disposed

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/lib/src/ffi/api/sumo/sign_sumo_ffi.dart
> +    final publicKey = _allocatePublicKey();
As commented in the api file, this should be a `SecureKeyFFI`, not a `Uint8List`

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/lib/src/js/api/sumo/sign_sumo_js.dart
> +    return jsErrorWrap(
Again, return a `SecretKeyJS` here

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/test/unit/ffi/api/sumo/sign_sumo_ffi_test.dart
> +      test('returns the public key of the secret key', () {
... returns the Curve25519 *secret key* of the ...

2023-07-13 04:54 UTC, Skycoder42 commented on packages/sodium/test/unit/js/api/sumo/sign_sumo_js_test.dart
> +      test('returns the curve25519 secret key of the ed25519 secret key', () {
Named correctly here, but still the wrong type

2023-07-28 21:20 UTC, f-person commented
Hi! Somehow I missed your reply and only noticed it when configuring a shortcut(?) in the GitHub mobile app :D 

Thanks for the review! I'll take a look soon and fix the code! 
Have a lovely day!

2023-09-26 16:05 UTC, rhbrunetto commented
@Skycoder42 are you working on this PR? If not I can try to find some time to help.

2026-06-04 14:54 UTC, f-person commented
i will close this PR as i don't intend to work on it. thanks for ur time reviewing, skycoder42 & apologies for it not being fruitful yet this time~

2026-06-04 14:54 UTC, closed without merging